<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['web_server_aliases'] = 'Псевдоним';
$lang['web_server_aliases_invalid'] = 'Поле псевдонимов является недействительным.';
$lang['web_server_app_description'] = 'Приложение Web Server может быть использовано для создания простых автономных веб-сайтов или как часть более широкой инфраструктуры для развертывания веб-приложений с использованием технологий, PHP, MySQL и Javascript.';
$lang['web_server_app_name'] = 'Веб Сервер';
$lang['web_server_configure_default_web_site'] = 'Настройка веб-сайта по умолчанию';
$lang['web_server_custom_configuration'] = 'Дополнительная настройка';
$lang['web_server_custom_configuration_warning'] = 'Старая или пользовательская конфигурационный файл был обнаружен, но вы все еще можете настроить параметры доступа для загрузки, используя веб-форму ниже. Нажмите на следующую кнопку, чтобы начать использовать стандартную конфигурацию, созданную приложением веб-сервера.';
$lang['web_server_directory_alias'] = 'Каталог Alias';
$lang['web_server_file_server_state_invalid'] = 'Состояние файлового сервера - инвалид.';
$lang['web_server_file_server_upload'] = 'Файловый сервер загрузка';
$lang['web_server_ftp_state_invalid'] = 'Состояние FTP - инвалид.';
$lang['web_server_ftp_upload'] = 'FTP загрузка';
$lang['web_server_group_invalid'] = 'Группа недействительна.';
$lang['web_server_hostname_aliases'] = 'Имя хоста Aliases';
$lang['web_server_live_site'] = 'Живой сайт';
$lang['web_server_review_standard_configuration'] = 'Обзор стандартной конфигурации';
$lang['web_server_server_name'] = 'Имя сервера';
$lang['web_server_server_name_invalid'] = 'Неверное имя сервера.';
$lang['web_server_site_invalid'] = 'Имя веб-узла является недействительным.';
$lang['web_server_test_site'] = 'Тест сайта';
$lang['web_server_upload_access'] = 'Доступ к загрузки';
$lang['web_server_web_application'] = 'Веб-приложений';
$lang['web_server_web_application_settings'] = 'Настройка веб-приложений';
$lang['web_server_web_applications'] = 'Веб-приложения';
$lang['web_server_web_server'] = 'Веб Сервер';
$lang['web_server_web_site'] = 'Веб сайт';
$lang['web_server_web_site_hostname'] = 'Имя хоста веб-сайта';
$lang['web_server_web_sites'] = 'Веб сайты';
