<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['web_server_aliases'] = 'Aliases';
$lang['web_server_aliases_invalid'] = 'Aliases field is invalid.';
$lang['web_server_app_description'] = 'The Web Server app can be used to create simple standalone web sites or as part of a broader infrastructure to deploy web-based applications using technologies like PHP, MySQL, and JavaScript.';
$lang['web_server_app_name'] = 'Web Server';
$lang['web_server_configure_default_web_site'] = 'Configure Default Web Site';
$lang['web_server_custom_configuration'] = 'Custom Configuration';
$lang['web_server_custom_configuration_warning'] = 'An old or custom configuration file was detected, but you can still configure the upload access settings using the web form below.  Click on the following button to start using the standard configuration generated by the Web Server app.';
$lang['web_server_directory_alias'] = 'Directory Alias';
$lang['web_server_file_server_state_invalid'] = 'File server state is invalid.';
$lang['web_server_file_server_upload'] = 'File Server Upload';
$lang['web_server_ftp_state_invalid'] = 'FTP state is invalid.';
$lang['web_server_ftp_upload'] = 'FTP Upload';
$lang['web_server_group_invalid'] = 'Group in invalid.';
$lang['web_server_hostname_aliases'] = 'Hostname Aliases';
$lang['web_server_live_site'] = 'Live Site';
$lang['web_server_review_standard_configuration'] = 'Review Standard Configuration';
$lang['web_server_server_name'] = 'Server Name';
$lang['web_server_server_name_invalid'] = 'Invalid server name.';
$lang['web_server_site_invalid'] = 'Web site name is invalid.';
$lang['web_server_test_site'] = 'Test Site';
$lang['web_server_upload_access'] = 'Upload Access';
$lang['web_server_web_application'] = 'Web Application';
$lang['web_server_web_application_settings'] = 'Web Application Settings';
$lang['web_server_web_applications'] = 'Web Applications';
$lang['web_server_web_server'] = 'Web Server';
$lang['web_server_web_site'] = 'Web Site';
$lang['web_server_web_site_hostname'] = 'Web Site Hostname';
$lang['web_server_web_sites'] = 'Web Sites';
