<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['web_server_aliases'] = 'Aliasy';
$lang['web_server_aliases_invalid'] = 'Wartość w polu Aliasy jest nieprawidłowa.';
$lang['web_server_app_description'] = 'Aplikacja Serwera WWW może być używana do tworzenia prostych, samodzielnych stron www lub też części szerszej infrastruktury np. do wdrażania aplikacji webowych korzystających z takich technologii jak PHP, MySQL czy JavaScript.';
$lang['web_server_app_name'] = 'Serwer WWW';
$lang['web_server_configure_default_web_site'] = 'Skonfiguruj domyślną stronę WWW';
$lang['web_server_custom_configuration'] = 'Konfiguracja niestandardowa';
$lang['web_server_custom_configuration_warning'] = 'Plik ze starą lub niestandardową konfiguracją został wykryty, ale nadal możesz skonfigurować ustawienia dostępu korzystając z formularza poniżej.  Kliknij w poniższy przycisk aby rozpocząć korzystanie ze standardowej konfiguracji wygenerowanej przez aplikację Serwera WWW.';
$lang['web_server_directory_alias'] = 'Alias Katalogu';
$lang['web_server_file_server_state_invalid'] = 'Stan serwera plików jest nieprawidłowy.';
$lang['web_server_file_server_upload'] = 'Wgrywanie na serwer plików';
$lang['web_server_ftp_state_invalid'] = 'Stan FTP jest nieprawidłowy';
$lang['web_server_ftp_upload'] = 'Wgrywanie na FTP';
$lang['web_server_group_invalid'] = 'Grupa jest nieprawidłowa.';
$lang['web_server_hostname_aliases'] = 'Aliasy nazwy hosta';
$lang['web_server_live_site'] = 'Uruchomiona strona';
$lang['web_server_review_standard_configuration'] = 'Przejrzyj standardową konfigurację';
$lang['web_server_server_name'] = 'Nazwa serwera';
$lang['web_server_server_name_invalid'] = 'Nieprawidłowa nazwa serwera.';
$lang['web_server_site_invalid'] = 'Nazwa strony WWW jest nieprawidłowa.';
$lang['web_server_test_site'] = 'Strona testowa';
$lang['web_server_upload_access'] = 'Dostęp do wgrywania';
$lang['web_server_web_application'] = 'Aplikacja webowa';
$lang['web_server_web_application_settings'] = 'Ustawienia aplikacji webowej';
$lang['web_server_web_applications'] = 'Aplikacje webowe';
$lang['web_server_web_server'] = 'Serwer WWW';
$lang['web_server_web_site'] = 'Strona WWW';
$lang['web_server_web_site_hostname'] = 'Nazwa hosta strony WWW';
$lang['web_server_web_sites'] = 'Strony WWW';
